project:
  name: "Text Summarizer"
  version: "1.0.0"
  description: "A project for summarizing text"
  author: "Shresth"
  license: "MIT"

model:
  name: "Falconsai/text_summarization"
  task: "summarization"
  parameters:
    max_length: 100
    min_length: 30
    do_sample: false

pipeline:
  framework: "transformers"
  batch_size: 8
  device: 0 

input:
  format: "text"
  max_input_length: 512  

output:
  format: "json"  
  directory: "outputs"  

logging:
  level: "INFO"
  log_file: "logs/summarizer.log"

api:
  enable: true
  host: "0.0.0.0"
  port: 5000

dependencies:
  python_version: ">=3.8"
  required_libraries:
    - "transformers>=4.30.0"
    - "pandas>=1.3.0"
    - "fastapi>=0.70.0"
    - "uvicorn>=0.15.0"

testing:
  enable_unit_tests: true
  test_data: "tests/test_data.json"

notes:
  - "Ensure GPU is available for better performance."
  - "Model is limited to 512 tokens. Split text if longer."